### ISSUE TITLE
compatability issue with Adventures in time

### ISSUE THREAD

**Issue by snail-001** [M-D-Team/k9#1]
k9 seems to be unable to enter the tardis, I couldn't get k9 to either follow me, or be pushed into the open tardis doors. the only mods installed were these two (k9 and AIT). not certain if immersive portals would fix this or not (or if its even compatible with AIT)

**Comment by Loqor** [comment]
Currently the tardis only teleports players, but I'm going to make it so it teleports all entities momentarily. immersive portals will fix this for now due to the fact that i've not implemented the aforementioned feature. also with k9, if you use the wristband he will follow you. p.s., the current version you're on is outdated, and once we finish our features we will release properly so sit tight!
